# Generated by Django 4.0.5 on 2022-07-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_i_am'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200, null=True)),
                ('event_date', models.DateField()),
                ('Online_link', models.CharField(blank=True, max_length=300, null=True)),
                ('event_location', models.CharField(blank=True, max_length=200, null=True)),
                ('Total_days_of_event', models.IntegerField()),
                ('group_name', models.ManyToManyField(to='core.group')),
            ],
        ),
    ]
