# Generated by Django 4.0.5 on 2022-07-21 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='group_name',
        ),
    ]
