# Generated by Django 4.0.5 on 2022-07-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_event_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
