# Generated by Django 4.0.5 on 2022-07-23 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_additional_qualifications_user_course_studied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='i_am',
        ),
        migrations.AddField(
            model_name='user',
            name='i_am',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.group'),
        ),
    ]
